### ISSUE TITLE
Payment scheme for PL 2016 AT

### ISSUE THREAD

**Issue by RosaLeeVV** [Open-Family-Policy-Platform/EU-SILC_CS#41]
As seen in comparing the LR&P for 2016 and 2018 for Austria, a new flexible payment scheme emerged after 2017. This affects almost all of the variables which I believe would need to be recoded to address the prior flat rate payment scheme in 2016. For instance, the amount (33.88 - 14.53 euros) and time span (365 - 851 days) was not mentioned for 2016.

**Comment by alzbetab** [comment]
ok, I will look into it as well.

**Comment by alzbetab** [comment]
There is a change but the change is not as massive as the LP&R makes it look. The year 2018 is coded according to MISSOC and I always code the most generous option if the parents can choose between different options. This usually means a replacement rate for employed/self-employed and the most generous flat-rate benefit for the inactive population.
