### ISSUE TITLE
PL 2016 CZ

### ISSUE THREAD

**Issue by RosaLeeVV** [Open-Family-Policy-Platform/EU-SILC_CS#52]
This one was pretty difficult. 
I have trouble finding the value for "If neither of the parents have social insurance: - €292/month." 

This may qualify is neither parent has sickness insurance (found in LR&P 2016):
If the daily assessment base cannot be set for any parent, Parental Allowance is paid at fixed monthly amounts of CZK 7,600 (€280) until the child reaches 10 months and afterwards at the amount of CZK 3,800 (€140) until the child is 48 months old.

However, I did not change this value because I was not sure if it was the correct replacement.

**Comment by alzbetab** [comment]
I will look into it.
