### ISSUE TITLE
ES PL 2016

### ISSUE THREAD

**Issue by RosaLeeVV** [Open-Family-Policy-Platform/EU-SILC_CS#72]
I suggested changes to the Basque region pl_ben1 based on LP&R 2016 information. However, LP&R 2018 information for parental leave for the Basque region also states that: "The amount of the benefit was not updated between 2012 and 2017 and income ceilings were introduced in 2015". Therefore, it seems that there is a discrepancy between the two and it might be possible that the benefits do not change for 2016 and 2018.

**Comment by alzbetab** [comment]
That's fine. Let's stick to what's in the source. Thank you!
